### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hiveliberty** [hiveliberty/Broadsword#7]
# Основное #
- [x] Rename and Message queues
- [x] Логика команды !auth (SSO Authorization)
- [x] Периодичной проверки авторизации (Periodic check authorization)
- [x] Логика проверки альянсовых\корпоративных писем (Periodic check alliance\corp mails)
